--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/vkamz597/InvMenu
build-by-default: true
branches:
- main
projects:
  libInvMenu:
    path: libInvMenu/
    model: virion
    type: library
...
